{% set name = "untwine" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hobuinc/untwine/archive/refs/tags/{{ version }}.tar.gz
  sha256: bb57ff485cdf588762b503edaeebd9d1db458095caaf64d95c3a4942a0c64a0a

build:
  number: 2

requirements:

  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
    - ninja
  host:
    - pdal
  run:
    - {{ pin_compatible('pdal', max_pin='x.x') }}
test:
  commands:
    - untwine --version
about:
  home: https://github.com/hobuinc/untwine
  summary: A command line utility for generating EPT and COPC point cloud data
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hobu
    - chambbj
