{% set name = "untwine" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hobuinc/untwine/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6dc1f6e3350745350413c3ea818f862d29ecaaaa35bf3b75e635a9260c9ccde3

build:
  number: 6
  skip: true  # [ppc64le]

requirements:

  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - ninja
  host:
    - libpdal-core
  run:
    - libpdal-core
test:
  commands:
    - untwine --version
about:
  home: https://github.com/hobuinc/untwine
  summary: A command line utility for generating EPT and COPC point cloud data
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hobu
    - chambbj
