{% set name = "untwine" %}
{% set version = "7.7.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hobuinc/untwine/archive/refs/tags/{{ version }}.tar.gz
  sha256: ded348d3653a40afff12a404ee2de36294587d4d0fad1ad34b05e1cad6ea63b0

build:
  number: 0
  skip: true  # [ppc64le]

requirements:

  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - ninja
  host:
    - libpdal-core
  run:
    - libpdal-core
test:
  commands:
    - untwine --version
about:
  home: https://github.com/hobuinc/untwine
  summary: A command line utility for generating EPT and COPC point cloud data
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hobu
    - chambbj
