{% set name = "untwine" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hobuinc/untwine/archive/refs/tags/{{ version }}.tar.gz
  sha256: 048c38f2b7759090587d1e569eadd06007d1a92dcb3c50854e24de1cb20f6f10

build:
  number: 1

requirements:

  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
    - ninja
  host:
    - pdal
  run:
    - {{ pin_compatible('pdal', max_pin='x.x.x') }}
test:
  commands:
    - untwine --version
about:
  home: https://github.com/hobuinc/untwine
  summary: A command line utility for generating EPT and COPC point cloud data
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hobu
    - chambbj
