{% set name = "untwine" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hobuinc/untwine/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6d3456c301a83d36052ea8b745c0b60c4ded975e148de4df5a07f28fd3a9d499

build:
  number: 0

requirements:

  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
    - ninja
  host:
    - pdal
  run:
    - {{ pin_compatible('pdal', max_pin='x.x.x') }}
test:
  commands:
    - untwine --version
about:
  home: https://github.com/hobuinc/untwine
  summary: A command line utility for generating EPT and COPC point cloud data
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hobu
    - chambbj
