schema_version: 1

context:
  name: untwine
  version: "1.5.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/hobuinc/untwine/archive/refs/tags/${{ version }}.tar.gz
  sha256: 69b5ef26a28c514b1a8459440f32faccc4fb2d3b835aa9733bf4d8c31a5f7022

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - cmake
    - make
    - ninja
  host:
    - libpdal-core
  run:
    - libpdal-core

tests:
  - script:
      - untwine --version

about:
  summary: A command line utility for generating EPT and COPC point cloud data
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://github.com/hobuinc/untwine

extra:
  recipe-maintainers:
    - hobu
    - chambbj
